import type { Supplier } from '~/types/studio'

/**
 * Mock supplier data — ready to replace with an external API call to the
 * provider dashboard (e.g. $fetch(config.providerApiUrl + '/suppliers')).
 * The structure is intentionally identical to the provider-panel contract.
 */
const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Cárnicas del Levante',
    description: 'Distribuidora cárnica con más de 20 años en el sector. Especialistas en ternera, cerdo y aves de corral criadas en la Comunitat Valenciana.',
    logo: '',
    location: 'Valencia, España',
    province: 'Valencia',
    categories: ['carnes'],
    rating: 4.8,
    reviewCount: 142,
    deliveryDays: 1,
    minOrderValue: 80,
    contactEmail: 'pedidos@carnicaslevante.es',
    contactPhone: '+34 963 111 222',
    website: 'https://carnicaslevante.es',
    verified: true,
    createdAt: '2024-01-10T09:00:00Z',
    products: [
      { id: 'sp-001-1', supplierId: 'sup-001', name: 'Ternera picada (bandeja 5 kg)', description: 'Ternera picada fresca, calidad extra', category: 'carnes', unit: 'kg', pricePerUnit: 8.5, minOrderQuantity: 5, maxOrderQuantity: 100, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-001-2', supplierId: 'sup-001', name: 'Pechuga de pollo fileteada', description: 'Pollo fresco de granja, sin piel', category: 'carnes', unit: 'kg', pricePerUnit: 5.9, minOrderQuantity: 5, maxOrderQuantity: 200, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-001-3', supplierId: 'sup-001', name: 'Costillas de cerdo ibérico', description: 'Costillas de cerdo ibérico de bellota, con DO', category: 'carnes', unit: 'kg', pricePerUnit: 11.2, minOrderQuantity: 3, maxOrderQuantity: 50, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-001-4', supplierId: 'sup-001', name: 'Bacon loncheado (kg)', description: 'Bacon ahumado en lonchas finas', category: 'carnes', unit: 'kg', pricePerUnit: 7.4, minOrderQuantity: 2, maxOrderQuantity: null, image: '', inStock: false, warehouseItemId: null },
    ],
  },
  {
    id: 'sup-002',
    name: 'Huerta Fresca SL',
    description: 'Agricultura ecológica y convencional del campo de Murcia. Recogida diaria y entrega en menos de 24 h. Certificación ecológica ES-ECO-020-MU.',
    logo: '',
    location: 'Murcia, España',
    province: 'Murcia',
    categories: ['verduras'],
    rating: 4.6,
    reviewCount: 98,
    deliveryDays: 1,
    minOrderValue: 40,
    contactEmail: 'ventas@huertafresca.es',
    contactPhone: '+34 968 333 444',
    website: 'https://huertafresca.es',
    verified: true,
    createdAt: '2024-02-05T08:00:00Z',
    products: [
      { id: 'sp-002-1', supplierId: 'sup-002', name: 'Tomate pera (caja 10 kg)', description: 'Tomate de temporada, calibre M-L', category: 'verduras', unit: 'kg', pricePerUnit: 1.2, minOrderQuantity: 10, maxOrderQuantity: 500, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-002-2', supplierId: 'sup-002', name: 'Cebolla blanca', description: 'Cebolla blanca de primera, sin brotes', category: 'verduras', unit: 'kg', pricePerUnit: 0.7, minOrderQuantity: 10, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-002-3', supplierId: 'sup-002', name: 'Lechuga Iceberg (ud)', description: 'Lechugas frescas calibradas, sin tierra', category: 'verduras', unit: 'unidades', pricePerUnit: 0.55, minOrderQuantity: 20, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-002-4', supplierId: 'sup-002', name: 'Patata monalisa (saco 25 kg)', description: 'Patata monalisa para freír o cocer', category: 'verduras', unit: 'kg', pricePerUnit: 0.45, minOrderQuantity: 25, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-002-5', supplierId: 'sup-002', name: 'Pimiento rojo (caja 5 kg)', description: 'Pimiento rojo mediano-grande, carnoso', category: 'verduras', unit: 'kg', pricePerUnit: 1.8, minOrderQuantity: 5, maxOrderQuantity: 200, image: '', inStock: false, warehouseItemId: null },
    ],
  },
  {
    id: 'sup-003',
    name: 'Lácteos del Norte',
    description: 'Quesería y lácteos artesanales de Asturias. Leche de vaca frisona de producción propia. Quesos, mantequillas y natas con denominación de origen.',
    logo: '',
    location: 'Oviedo, Asturias',
    province: 'Asturias',
    categories: ['lácteos'],
    rating: 4.7,
    reviewCount: 63,
    deliveryDays: 2,
    minOrderValue: 60,
    contactEmail: 'info@lacteosdelnorte.es',
    contactPhone: '+34 985 555 666',
    website: 'https://lacteosdelnorte.es',
    verified: true,
    createdAt: '2024-03-01T10:00:00Z',
    products: [
      { id: 'sp-003-1', supplierId: 'sup-003', name: 'Leche entera (brik 1 L)', description: 'Leche entera pasteurizada de vaca', category: 'lácteos', unit: 'L', pricePerUnit: 0.85, minOrderQuantity: 12, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-003-2', supplierId: 'sup-003', name: 'Nata para cocinar 35% (L)', description: 'Nata líquida para cocinar, alta cremosidad', category: 'lácteos', unit: 'L', pricePerUnit: 2.1, minOrderQuantity: 6, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-003-3', supplierId: 'sup-003', name: 'Mantequilla sin sal (250 g)', description: 'Mantequilla artesana sin sal, en bloque', category: 'lácteos', unit: 'unidades', pricePerUnit: 1.9, minOrderQuantity: 10, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-003-4', supplierId: 'sup-003', name: 'Queso parmesano rallado (kg)', description: 'Parmesano importado, rallado grueso', category: 'lácteos', unit: 'kg', pricePerUnit: 14.5, minOrderQuantity: 1, maxOrderQuantity: 20, image: '', inStock: true, warehouseItemId: null },
    ],
  },
  {
    id: 'sup-004',
    name: 'Panadería Artesana Madrid',
    description: 'Obrador artesano en Madrid. Pan de masa madre, bollería y bases de pizza horneados cada madrugada. Distribución propia en la Comunidad de Madrid y alrededores.',
    logo: '',
    location: 'Madrid, España',
    province: 'Madrid',
    categories: ['panadería'],
    rating: 4.5,
    reviewCount: 211,
    deliveryDays: 1,
    minOrderValue: 50,
    contactEmail: 'obrador@panartesanomadrid.es',
    contactPhone: '+34 915 777 888',
    website: 'https://panartesanomadrid.es',
    verified: false,
    createdAt: '2024-01-20T07:00:00Z',
    products: [
      { id: 'sp-004-1', supplierId: 'sup-004', name: 'Pan brioche (ud 600 g)', description: 'Pan brioche esponjoso, sin conservantes', category: 'panadería', unit: 'unidades', pricePerUnit: 2.8, minOrderQuantity: 5, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-004-2', supplierId: 'sup-004', name: 'Base pizza fina (pack 5 ud)', description: 'Bases de pizza fina prehorneadas Ø 30 cm', category: 'panadería', unit: 'unidades', pricePerUnit: 1.1, minOrderQuantity: 20, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-004-3', supplierId: 'sup-004', name: 'Pan de hamburguesa (ud)', description: 'Pan de hamburguesa con semillas de sésamo', category: 'panadería', unit: 'unidades', pricePerUnit: 0.45, minOrderQuantity: 48, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
    ],
  },
  {
    id: 'sup-005',
    name: 'Salsas y Especias Ibéricas',
    description: 'Fábrica de salsas y condimentos en Sevilla. Más de 80 referencias: salsas base, aliños, especias, vinagres y aceites. Clientes en más de 500 restaurantes nacionales.',
    logo: '',
    location: 'Sevilla, España',
    province: 'Sevilla',
    categories: ['salsas'],
    rating: 4.4,
    reviewCount: 175,
    deliveryDays: 3,
    minOrderValue: 70,
    contactEmail: 'ventas@salsasibericas.es',
    contactPhone: '+34 954 222 333',
    website: 'https://salsasibericas.es',
    verified: true,
    createdAt: '2023-11-15T09:00:00Z',
    products: [
      { id: 'sp-005-1', supplierId: 'sup-005', name: 'Tomate frito industrial (5 kg)', description: 'Tomate frito español de gran formato', category: 'salsas', unit: 'kg', pricePerUnit: 3.2, minOrderQuantity: 5, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-005-2', supplierId: 'sup-005', name: 'Aceite de oliva virgen extra (5 L)', description: 'AOVE andaluz, acidez < 0.2°', category: 'salsas', unit: 'L', pricePerUnit: 6.5, minOrderQuantity: 5, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-005-3', supplierId: 'sup-005', name: 'Salsa BBQ ahumada (bote 2.5 kg)', description: 'Salsa barbacoa ahumada para gastronomía', category: 'salsas', unit: 'kg', pricePerUnit: 4.8, minOrderQuantity: 3, maxOrderQuantity: null, image: '', inStock: false, warehouseItemId: null },
      { id: 'sp-005-4', supplierId: 'sup-005', name: 'Mix de especias mediterráneas (kg)', description: 'Blend de orégano, albahaca, tomillo y romero', category: 'salsas', unit: 'kg', pricePerUnit: 9.9, minOrderQuantity: 1, maxOrderQuantity: 20, image: '', inStock: true, warehouseItemId: null },
    ],
  },
  {
    id: 'sup-006',
    name: 'Bebidas Mediterráneo',
    description: 'Distribuidor de bebidas en Barcelona. Agua, refrescos, cervezas artesanas, zumos naturales y bebidas sin alcohol. Logística refrigerada propia en toda Cataluña.',
    logo: '',
    location: 'Barcelona, España',
    province: 'Barcelona',
    categories: ['bebidas'],
    rating: 4.3,
    reviewCount: 88,
    deliveryDays: 2,
    minOrderValue: 100,
    contactEmail: 'pedidos@bebidasmediterraneo.es',
    contactPhone: '+34 933 444 555',
    website: 'https://bebidasmediterraneo.es',
    verified: true,
    createdAt: '2024-04-01T08:00:00Z',
    products: [
      { id: 'sp-006-1', supplierId: 'sup-006', name: 'Agua mineral 50 cl (caja 24 ud)', description: 'Agua mineral natural sin gas', category: 'bebidas', unit: 'unidades', pricePerUnit: 0.22, minOrderQuantity: 24, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-006-2', supplierId: 'sup-006', name: 'Cerveza artesana IPA (L)', description: 'Cerveza artesana tipo IPA, 6.2% vol.', category: 'bebidas', unit: 'L', pricePerUnit: 3.9, minOrderQuantity: 10, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-006-3', supplierId: 'sup-006', name: 'Zumo de naranja natural (L)', description: 'Zumo NFC sin azúcar añadido, refrigerado', category: 'bebidas', unit: 'L', pricePerUnit: 2.1, minOrderQuantity: 10, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
      { id: 'sp-006-4', supplierId: 'sup-006', name: 'Refresco cola lata 33 cl (pack 24)', description: 'Refresco de cola en lata estándar', category: 'bebidas', unit: 'unidades', pricePerUnit: 0.48, minOrderQuantity: 24, maxOrderQuantity: null, image: '', inStock: true, warehouseItemId: null },
    ],
  },
]

export default defineEventHandler(async (_event) => {
  /**
   * TODO (producción): reemplazar con llamada al panel externo de proveedores:
   * const config = useRuntimeConfig()
   * return $fetch<Supplier[]>(`${config.providerApiUrl}/suppliers`)
   */
  return MOCK_SUPPLIERS
})
